### PR TITLE
Catch exception while installing TYPO3 extension

### PR DESCRIPTION
**Pull request by sascha-egerer**
If a TYPO3 extension has modified files while running composer update the process
ends hard with an exception and not further changes are made. Exceptions should
be cachtched so the process can continue and update at least all other packages

### CODE REVIEW

**Comment by helhum** [comment]
>  so the process can continue and update at least all other packages

for me the question is, how the composer library installer handles that case.
I tried it and when `--no-interaction` is specified, the installation / update is stopped, which, from a package manager perspective is the safest thing to do.

So if there are setups where this imposes a problem, these setups should be modified.

**Comment by sascha-egerer** [comment]
I think that depends on the option `discard-changes` https://getcomposer.org/doc/06-config.md#discard-changes
Is that possible?

**Comment by helhum** [comment]
> Is that possible?

Yes, true. But in any case composer updates the code (changes are discarded or stashed), or it stops execution. The PR here just ignores the changes and leaves the code in undefined state. That might work for edge cases, but may be harmful in other cases.

I'll re-open the pr, but mark it as needs changes.

TODO:

* evaluate that config and act accordingly in our installer
* introduce code that is able to handle the "stash" case
* introduce code that is able to handle the "discard" case

**Comment by helhum** [comment]
Anybody wants to pick up this one and work on the [open topics](https://github.com/TYPO3/CmsComposerInstallers/pull/58#pullrequestreview-9821133)?

If not, I tend to close this again.

**Comment by sascha-egerer** [comment]
I'm fine with closing it.

**Pull request closed without merging**
