### PR TITLE
Respect "installer-name" inside "extra"

### PR DESCRIPTION
**Pull request by vandres**

### CODE REVIEW

**Comment by helhum** [comment]
What is wrong to write a replace section in the composer.json?

**Comment by vandres** [comment]
Don't know what the recommended way is. "installer-name" is the "composer/installers" way

**Comment by helhum** [comment]
> Don't know what the recommended way is. "installer-name" is the "composer/installers" way

The replaces section works and is respected by the TYPO3 installer.
What do you think are the benefits to add the "composer/installers way"?

**Comment by vandres** [comment]
the benefit is a consistence api for people working with other technologies then TYPO3.

**Comment by mbrodala** [comment]
@vandres Do you have a specific usecase where the existing logic is not able to determine the correct extension key?

**Comment by cedricziel** [comment]
I vote for adding this as well. Link to the relevant README entry: https://github.com/composer/installers/blob/41a2376f1c67d1cc3bdf498eaea2f364d02b26f3/README.md#custom-install-names

If I were to maintain 2 `project` packages named `cedricziel/customer1-project` and `cedricziel/customer2-project` i'd expect to be able to have a resulting extension name `project` in the respective project. In fact `cedricziel/customer1-project` wouldnt replace `project`, it then _is_ the `project` extension.

Apart from that - replace will still work, but I think it's a good idea to stick to the `installer-name` convention.

**Comment by helhum** [comment]
> If I were to maintain 2 project packages named cedricziel/customer1-project and cedricziel/customer2-project i'd expect to be able to have a resulting extension name project in the respective project. In fact cedricziel/customer1-project wouldnt replace project, it then is the project extension.

Sounds fishy and like an edge use case ;)

It is also not where we are heading. The goal is, that TYPO3 works whereever an extension is installed and whatever its directory name is. So I'd like to not add another way to configure the extension key.

**Comment by helhum** [comment]
It is btw. now possible to configure the extension directory to be the package name and set up the required directory structure manually. Besides that, I finally documented the options, requirements and behavior of the installer in the README, to get people from other technologies on board more easily.

**Comment by helhum** [comment]
Uhm, better late than never, right? :)

**Comment by vandres** [comment]
wohoo :D Thanks

**Comment by cedricziel** [comment]
Great, thx! :)

**Pull request closed without merging**
