### PR TITLE
[FEATURE] Activate cache for extension downloads

### PR DESCRIPTION
**Pull request by jaguerra**
Relates: #65495

### CODE REVIEW

**Comment by jaguerra** [comment]
Guys, any chance of pushing this up? Thanks!

BTW if you need a helping hand here count me in

**Comment by KampfCaspar** [comment]
pulling a feature branch instead of master might expediate it.

**Comment by StephenKing** [comment]
Thanks for your contribution, @jaguerra.

TYPO3 is not using Github for development, but Gerrit Code Review system at https://review.typo3.org. Would you please be so kind and push your code there? A tutorial can be found [here](http://wiki.typo3.org/Contribution_Walkthrough_Tutorials).

**Comment by tmaroschik** [comment]
@StephenKing The development of the cms composer installer happens on Github. So this is exactly the right place. But thanks for taking care of the reply.

@jaguerra I'm unfortunately short of time currently, but your change looks good. Maybe @helhum can take car of testing and merging the pull request?

**Comment by jaguerra** [comment]
Thanks for the feedback :)

**Comment by StephenKing** [comment]
Ah ouch. Sorry, too many repos I'm not involved but notified for..

**Comment by helhum** [comment]
Tested. Works perfect, thanks!

**Comment by jaguerra** [comment]
Great! Thank you! 👍🎉

**Pull request merged**
